In [ ]:
import numpy as np
docs=["go bangladesh",
     "bangladesh bangladesh",
     "hip hip hurray",
     "jitbe ebar jitbe cricket",
     "bangladesh jindabad",
     "sakib sakib",
     "mehedi mehedi",
     "tamim tamim",
     "allahuakbar allahuakbar"]

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

12

In [ ]:
sequences=tokenizer.texts_to_sequences(docs)

In [ ]:
sequences

[[8, 1],
 [1, 1],
 [2, 2, 9],
 [3, 10, 3, 11],
 [1, 12],
 [4, 4],
 [5, 5],
 [6, 6],
 [7, 7]]

In [ ]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequences,padding="post")

In [ ]:
sequences

array([[ 8,  1,  0,  0],
       [ 1,  1,  0,  0],
       [ 2,  2,  9,  0],
       [ 3, 10,  3, 11],
       [ 1, 12,  0,  0],
       [ 4,  4,  0,  0],
       [ 5,  5,  0,  0],
       [ 6,  6,  0,  0],
       [ 7,  7,  0,  0]], dtype=int32)

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding

In [ ]:
model = Sequential()
model.add(Embedding(12,output_dim=2,input_length=4)) #output_dim means per word represent through 2 numbers

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 4, 2)              24        
                                                                 
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile("adam","accuracy")

In [ ]:
pred=model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 27ms/step
[[[ 0.00288472  0.0400121 ]
  [-0.03950218 -0.04147893]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[-0.03950218 -0.04147893]
  [-0.03950218 -0.04147893]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[ 0.02948235  0.01483282]
  [ 0.02948235  0.01483282]
  [-0.04304504  0.03124309]
  [ 0.02592529 -0.03692202]]

 [[-0.02507217 -0.02518055]
  [-0.04031881  0.01862084]
  [-0.02507217 -0.02518055]
  [-0.00393897  0.03787397]]

 [[-0.03950218 -0.04147893]
  [ 0.          0.        ]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[ 0.02247579 -0.02935169]
  [ 0.02247579 -0.02935169]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[ 0.01119586 -0.0464241 ]
  [ 0.01119586 -0.0464241 ]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[-0.00224936 -0.04344009]
  [-0.00224936 -0.04344009]
  [ 0.02592529 -0.03692202]
  [ 0.02592529 -0.03692202]]

 [[ 0.00635096  0.04545475]
  [ 0.00

In [ ]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 2s 0us/step


In [ ]:
X_train=pad_sequences(X_train,padding="post",maxlen=50)
X_test=pad_sequences(X_test,padding="post",maxlen=50) 

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model=Sequential()
model.add(Embedding(10000,2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 42s 50ms/step - loss: 0.6266 - accuracy: 0.6120 - val_loss: 0.4622 - val_accuracy: 0.7856
Epoch 2/5
782/782 [==============================] - 41s 52ms/step - loss: 0.4012 - accuracy: 0.8232 - val_loss: 0.4165 - val_accuracy: 0.8111
Epoch 3/5
782/782 [==============================] - 39s 50ms/step - loss: 0.3301 - accuracy: 0.8632 - val_loss: 0.4234 - val_accuracy: 0.8108
Epoch 4/5
782/782 [==============================] - 39s 50ms/step - loss: 0.2900 - accuracy: 0.8846 - val_loss: 0.4514 - val_accuracy: 0.7929
Epoch 5/5
782/782 [==============================] - 39s 50ms/step - loss: 0.2657 - accuracy: 0.8978 - val_loss: 0.4931 - val_accuracy: 0.7976
